 
version: '3.8'

services:

  go_webserver:
    image: practicasdedesarrollounq/go_webserver:1.0.4
    container_name: go_webserver_compose
    ports:
      - "9091:9091"
    depends_on:
      - mysql
      - redis
    networks:
      - mynet
  node:
    image: node:lts-slim
    container_name: node
    volumes:
      - node_data:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    networks:
      - mynet

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynet

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - mynet

networks:
  mynet:

volumes:
  node_data:
  mysql_data:
  redis_data:
